name: build test created with vs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore CreatedWithVs\CreatedWithVs.sln
    - name: Build
      run: dotnet build CreatedWithVs\CreatedWithVs.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test CreatedWithVs\CreatedWithVs.sln --no-build --verbosity normal --configuration Release
